<?php
$z[0]=Array("global","",193,219);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\"<em></em>\":@me=\"\";",278,362);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n      	<a href='[field:typeurl/]'>[field:typename/]</a>\r\n      	",372,547);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<a href='~typelink~'><em></em>~typename~</a>";
$z[3]=Array("global","",654,679);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",937,963);
$z[4][4]['name']="cfg_cmspath";

?>